package com.ghosterdex.wallet.crypto

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.util.Locale

/**
 * Known-answer tests for the TON signing path.
 *
 * Every expected value here was produced by the mini app's own dependencies
 * (`@ton/crypto`, `@ton/ton`, `tweetnacl`) and by re-implementing the Worker's
 * `verifyWalletSig` preimage exactly. So these do not test that the Kotlin is
 * self-consistent. They test that it agrees with the code already in
 * production. That is the only property that matters: a wallet that derives a
 * different address, or signs a different preimage, is silently useless.
 */
@RunWith(AndroidJUnit4::class)
class TonVectorsTest {

    private val context get() = InstrumentationRegistry.getInstrumentation().targetContext

    private fun hex(b: ByteArray) = b.joinToString("") { String.format(Locale.ROOT, "%02x", it) }
    private fun unhex(s: String) = ByteArray(s.length / 2) {
        ((Character.digit(s[it * 2], 16) shl 4) or Character.digit(s[it * 2 + 1], 16)).toByte()
    }

    /** Generated by @ton/crypto's mnemonicNew(); passes TON's seed-version check. */
    private val validMnemonic =
        "soda ripple wire snap lift castle balance train short machine another mystery " +
            "buzz side pact random west loop fat mesh hollow purpose replace excuse"

    /** Well-formed words, but fails isBasicSeed. MnemonicValidate() returns false. */
    private val invalidMnemonic =
        "dose ice enrich trigger test dove century still betray gas diet dune " +
            "ready oyster junk symbol lawsuit fine cluster garden bind nut cross hero"

    // ── Derivation ───────────────────────────────────────────────────────────

    @Test
    fun tonMnemonic_derivesPrivateScalar_matchesTonCrypto() {
        val scalar = TonMnemonic.toPrivateKey(validMnemonic.toCharArray())
        assertEquals("e3fc98460c61e3c13afee01bf67c8b61daac8a765f1c21866db358666e0addd0", hex(scalar))
    }

    @Test
    fun tonKey_publicKeyAndAddress_matchWalletContractV4() {
        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            assertEquals(
                "1f30a0f735f86ec3f0c7f2c1d7db28df2985342bf73b59b379a9274dfa7c152c",
                key.publicKeyHex,
            )
            // The address is sha256 over the state-init cell, so this passing
            // also proves TonCell's representation hashing and the precomputed
            // v4R2 code hash/depth constants are correct.
            assertEquals(
                "0:40a42ae8d0aea047bb718e1d04a5b7c2af161b3c5225f56f874a46170e17a21c",
                key.addressRaw,
            )
        }
    }

    /**
     * Every contract version, against `@ton/ton`.
     *
     * The same key gives three unrelated addresses. Deriving only one means a
     * user who imports a Tonkeeper wallet. Which has defaulted to V5R1 since
     * the W5 standard landed in July 2024. Sees an empty balance while their
     * funds sit safely at an address the app never queries.
     */
    @Test
    fun tonKey_allContractVersions_matchTonLibrary() {
        TonKey.fromMnemonicNative(validMnemonic.toCharArray()).use { key ->
            val candidates = key.candidateAddresses()
            assertEquals(
                "0:dcced75998cdf8dcb53977aa51b9e91b6cfdc7d5dfb41d7d22424a675fbb6dce",
                candidates[TonWalletVersion.V5R1],
            )
            assertEquals(
                "0:40a42ae8d0aea047bb718e1d04a5b7c2af161b3c5225f56f874a46170e17a21c",
                candidates[TonWalletVersion.V4R2],
            )
            assertEquals(
                "0:1f20f387f972de5891f9b385e88c979a69154bf2b89afb92a8702ed4035f48ab",
                candidates[TonWalletVersion.V3R2],
            )
            // Three versions, three distinct addresses. Which is the entire
            // reason import has to probe rather than assume.
            assertEquals(3, candidates.values.toSet().size)
        }
    }

    @Test
    fun tonKey_defaultsToTheEcosystemDefault() {
        // New wallets must land where Tonkeeper and friends would put them, so
        // a user importing this phrase elsewhere finds the same address.
        assertEquals(TonWalletVersion.V5R1, TonWalletVersion.DEFAULT)
        TonKey.fromMnemonicNative(validMnemonic.toCharArray()).use { key ->
            assertEquals(TonWalletVersion.V5R1, key.version)
            assertEquals(
                "0:dcced75998cdf8dcb53977aa51b9e91b6cfdc7d5dfb41d7d22424a675fbb6dce",
                key.addressRaw,
            )
        }
    }

    @Test
    fun tonKey_secondVector_matches() {
        TonKey.fromMnemonicNative(invalidMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            assertEquals(
                "b94c3c8ec967be12a300eb9bcb1e221b590665d83b0d94c45856b1f6fab3ad3b",
                key.publicKeyHex,
            )
            assertEquals(
                "0:a1d323e412f0beceb546800516ec809c96b8d59c2cfa5d4b09b8e284d0c891a5",
                key.addressRaw,
            )
        }
    }

    @Test
    fun tonMnemonic_isNotBip39() {
        // Same words, different algorithm. If these ever matched it would mean
        // one of the two implementations had silently become the other.
        val ton = TonMnemonic.toPrivateKey(validMnemonic.toCharArray())
        val bip39Seed = Bip39.toSeed(validMnemonic.toCharArray())
        assertNotEquals(hex(ton), hex(bip39Seed.copyOfRange(0, 32)))
    }

    // ── Validation ───────────────────────────────────────────────────────────

    @Test
    fun tonMnemonic_validate_matchesTonCryptoVerdicts() {
        assertTrue(TonMnemonic.validate(context, validMnemonic.toCharArray()))
        // @ton/crypto's mnemonicValidate() returns false for this one.
        assertFalse(TonMnemonic.validate(context, invalidMnemonic.toCharArray()))
        // Word not in the list.
        assertFalse(
            TonMnemonic.validate(context, validMnemonic.replace("soda", "ghosterdex").toCharArray()),
        )
        // TON mnemonics are always 24 words.
        assertFalse(TonMnemonic.validate(context, "soda ripple wire".toCharArray()))
    }

    @Test
    fun tonMnemonic_generate_producesValidMnemonics() {
        val generated = TonMnemonic.generate(context)
        assertEquals(24, String(generated).split(" ").size)
        assertTrue(TonMnemonic.validate(context, generated))
    }

    // ── Cell hashing ─────────────────────────────────────────────────────────

    @Test
    fun tonCell_dataCellHash_matchesTonCore() {
        // seqno(0,32) || walletId(698983191,32) || pubkey(256) || 0(1) = 321 bits
        val pub = unhex("b94c3c8ec967be12a300eb9bcb1e221b590665d83b0d94c45856b1f6fab3ad3b")
        val data = ByteArray(41)
        // 698983191 == 0x29A9A317
        data[4] = 0x29; data[5] = 0xA9.toByte(); data[6] = 0xA3.toByte(); data[7] = 0x17
        System.arraycopy(pub, 0, data, 8, 32)

        val ref = TonCell.hash(data, 321)
        assertEquals("79179f19467f0fa17cba57fe6103813349ceb96b568c2519f1b6daef5320fe53", hex(ref.hash))
        assertEquals(0, ref.depth)
    }

    @Test
    fun tonCell_augmentationChangesHash() {
        // "5 bits" and "8 bits with three trailing zeros" must not collide -
        // that is exactly what the augmentation bit exists to prevent.
        val a = TonCell.hash(byteArrayOf(0b00110_000.toByte()), 5)
        val b = TonCell.hash(byteArrayOf(0b00110_000.toByte()), 8)
        assertNotEquals(hex(a.hash), hex(b.hash))
    }

    // ── TON Connect signData ─────────────────────────────────────────────────

    @Test
    fun signData_matchesWorkerPreimageAndSignature() {
        val text = "GhosterDex withdrawal\n50 USDT to EQtest\non TON\nReject if you did not start this."

        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            val sig = TonConnectSigner.signText(
                key = key,
                text = text,
                domain = "ghosterdex.com",
                timestamp = 1753000000L,
            )

            // Ed25519 is deterministic, so a correct implementation reproduces
            // this byte for byte. Any drift in the preimage changes it entirely.
            assertEquals(
                "twPZKOe7p+PIOuQvoevcklHjU10/oC/RyWFbEo3Ym42YLRzmnyUdVLf2+AxhfzSsQdyrnNbkE8tTwahN4kBJDg==",
                sig.signatureBase64,
            )
            assertEquals("0:40a42ae8d0aea047bb718e1d04a5b7c2af161b3c5225f56f874a46170e17a21c", sig.address)
            assertEquals(1753000000L, sig.timestamp)
            assertEquals("ghosterdex.com", sig.domain)
            assertEquals(text, sig.text)
        }
    }

    // ── TON Connect ton_proof (wallet login) ─────────────────────────────────

    @Test
    fun tonProof_matchesWorkerDigestAndSignature() {
        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            val proof = TonProofSigner.sign(
                key = key,
                domain = "ghosterdex.com",
                payload = "ghoster-challenge-abc123",
                timestamp = 1753000000L,
            )
            // Byte-identical to what worker/index.ts tonProofDigest() verifies.
            // Getting the mixed endianness wrong changes this entirely.
            assertEquals(
                "jXcG7PLsk+YZ4nHqjQ48FUbqocnlJV7/CePMoi9SDPyIIDOtZ8Qtf0PruMTP95v/bseDvI4sWwmzRS2PrVBcCA==",
                proof.signatureBase64,
            )
            assertEquals(1753000000L, proof.timestamp)
            assertEquals("ghosterdex.com", proof.domainValue)
            assertEquals(14, proof.domainLengthBytes)
            assertEquals("ghoster-challenge-abc123", proof.payload)
        }
    }

    @Test
    fun tonProof_isADifferentEnvelopeFromSignData() {
        // Same key, same domain, same timestamp, same string. If these ever
        // matched, one signer would be using the other's envelope. And the
        // server would reject every login or every transaction.
        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            val text = "ghoster-challenge-abc123"
            val proof = TonProofSigner.sign(key, "ghosterdex.com", text, 1753000000L)
            val data = TonConnectSigner.signText(key, text, "ghosterdex.com", 1753000000L)
            assertNotEquals(proof.signatureBase64, data.signatureBase64)
        }
    }

    @Test
    fun tonProof_payloadIsBoundIntoTheSignature() {
        // The server-issued challenge is what makes the proof unreplayable.
        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            val a = TonProofSigner.sign(key, "ghosterdex.com", "challenge-a", 1753000000L)
            val b = TonProofSigner.sign(key, "ghosterdex.com", "challenge-b", 1753000000L)
            assertNotEquals(a.signatureBase64, b.signatureBase64)
        }
    }

    @Test
    fun signData_anyFieldChange_changesSignature() {
        val text = "GhosterDex withdrawal\n50 USDT to EQtest\non TON\nReject if you did not start this."
        TonKey.fromMnemonicNative(validMnemonic.toCharArray(), version = TonWalletVersion.V4R2).use { key ->
            val base = TonConnectSigner.signText(key, text, "ghosterdex.com", 1753000000L)

            // The domain and timestamp are inside the signed preimage, so a
            // signature cannot be replayed for another origin or another moment.
            assertNotEquals(
                base.signatureBase64,
                TonConnectSigner.signText(key, text, "evil.example", 1753000000L).signatureBase64,
            )
            assertNotEquals(
                base.signatureBase64,
                TonConnectSigner.signText(key, text, "ghosterdex.com", 1753000001L).signatureBase64,
            )
            assertNotEquals(
                base.signatureBase64,
                TonConnectSigner.signText(key, "$text ", "ghosterdex.com", 1753000000L).signatureBase64,
            )
        }
    }
}
